language: java
sudo: false

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - qrioflat@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

addons:
  postgresql: "10"

services:
  - postgresql

before_install:
  - psql -c 'create database todolist;' -U postgres
  - sudo -u postgres psql -c "ALTER ROLE postgres WITH password 'password'"

jdk:
  - oraclejdk14